name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12', '14']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm audit --only=prod --audit-level=high
      - run: npm run lint
      - run: npm run build
      - run: npm run test:coverage
      - run: npm run test:codecov
      - run: npm run docs
      - name: Deploy docs to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs
